name: Docker Image CI

on: [push, pull_request]

jobs:

  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag standardversion:buildcandidate
    - name: Ensure Standard Version can execute
      run: docker run standardversion:buildcandidate --version
