name: Standard Version

on:
  push:
    branches: [ master ]

jobs:

  version:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update version
      run: docker run -v $(pwd):/repo ckxng/standardversion
    - name: Push repo
      run: git push --follow-tags origin master